mysql:
  image: mysql:5.7.20
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init_connect='SET NAMES utf8mb4' --innodb-flush-log-at-trx-commit=0
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  volumes:
    - ./log/mysql.log:/var/log/mysqld.log
  environment:
    - MYSQL_ROOT_PASSWORD=monotoday
    - MYSQL_DATABASE=monotoday
    - MYSQL_ROOT_HOST=%

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

app:
  build: .
  environment:
    RAILS_ENV: development
  ports:
    - '80:3000'
  volumes_from:
    - appdata
  links:
    - "mysql"

appdata:
  image: tianon/true
  volumes:
    - ".:/workspace"
